// tests/license.test.mjs
// JWT license verification tests for CE's utils/license.mjs.
// Test fixture JWTs were generated by the license-manager's keygen CLI
// and signed with the real ES256 private key.

import { describe, it, before, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getTierFromEnv, loadLicense, _resetCache } from '../utils/license.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LICENSE_MANAGER = join(__dirname, '..', '..', 'nsauditor-ai-license-manger');

// ── Test Fixture JWTs ───────────────────────────────────────────────────────
// Real JWTs signed with the production EC key pair (expire ~2036).

const VALID_PRO_KEY = 'pro_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWVyIjoicHJvIiwib3JnIjoidGVzdC1wcm9AZml4dHVyZS5jb20iLCJzZWF0cyI6MSwibGljZW5zZUlkIjoibGljXzM0ODRlZjU4LWYzMjUtNDUxOS04NjY5LTIzYjY3M2Y0YjZkYyIsImNhcGFiaWxpdGllcyI6WyJpbnRlbGxpZ2VuY2VFbmdpbmUiLCJyaXNrU2NvcmluZyIsInByb0FJIiwicHJvTUNQIiwiYW5hbHlzaXNBZ2VudHMiLCJ2ZXJpZmljYXRpb25FbmdpbmUiLCJhZHZhbmNlZENURU0iLCJlbmhhbmNlZFJlZGFjdGlvbiIsInBkZkV4cG9ydCIsImJyYW5kZWRSZXBvcnRzIl0sInN1YiI6ImxpY2Vuc2UiLCJpc3MiOiJuc2Fzb2Z0IiwiYXVkIjoibnNhdWRpdG9yLWFpIiwiaWF0IjoxNzc2MjA3MzI3LCJleHAiOjIwOTE1NjczMjd9.qt3wIqVShLAS2TdtFmY7_MvIFb0dEbpQ2AG-FiAxgp0VR7h9CJv2CG_FfXjPipd4f0n6QDkcv8pungZvK8BKZA';

const VALID_ENTERPRISE_KEY = 'enterprise_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWVyIjoiZW50ZXJwcmlzZSIsIm9yZyI6IlRlc3QgRW50ZXJwcmlzZSBDb3JwIiwic2VhdHMiOjI1LCJsaWNlbnNlSWQiOiJsaWNfMmVlNDU1ODctYTEzYy00ODcwLWIzNjMtMzhmNmNmNjMwNmE5IiwiY2FwYWJpbGl0aWVzIjpbImludGVsbGlnZW5jZUVuZ2luZSIsInJpc2tTY29yaW5nIiwicHJvQUkiLCJwcm9NQ1AiLCJhbmFseXNpc0FnZW50cyIsInZlcmlmaWNhdGlvbkVuZ2luZSIsImFkdmFuY2VkQ1RFTSIsImVuaGFuY2VkUmVkYWN0aW9uIiwicGRmRXhwb3J0IiwiYnJhbmRlZFJlcG9ydHMiLCJjbG91ZFNjYW5uZXJzIiwiemVyb1RydXN0IiwiY29tcGxpYW5jZUVuZ2luZSIsInpkZVBvbGljeUVuZ2luZSIsImVudGVycHJpc2VDVEVNIiwiZW50ZXJwcmlzZU1DUCIsInVzYWdlTWV0ZXJpbmciLCJhaXJHYXBwZWQiLCJkb2NrZXJJc29sYXRpb24iXSwic3ViIjoibGljZW5zZSIsImlzcyI6Im5zYXNvZnQiLCJhdWQiOiJuc2F1ZGl0b3ItYWkiLCJpYXQiOjE3NzYyMDczMzAsImV4cCI6MjA5MTU2NzMzMH0.nUTUQEzvUiERCLK-MNJ7hbwyJCgAOp_AzPjtEnNEB1gNYTbyHFoVpmwA_1PqGzxs_pdlfwbDJz-k8wdSPAgN1Q';

// Expired 1 hour ago (well beyond 120s clock tolerance)
const EXPIRED_PRO_KEY = 'pro_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWVyIjoicHJvIiwib3JnIjoiZXhwaXJlZEBmaXh0dXJlLmNvbSIsInNlYXRzIjoxLCJsaWNlbnNlSWQiOiJsaWNfZXhwaXJlZC1maXh0dXJlIiwiY2FwYWJpbGl0aWVzIjpbImludGVsbGlnZW5jZUVuZ2luZSJdLCJzdWIiOiJsaWNlbnNlIiwiaXNzIjoibnNhc29mdCIsImF1ZCI6Im5zYXVkaXRvci1haSIsImlhdCI6MTc3NjIwMDE0OSwiZXhwIjoxNzc2MjAzNzQ5fQ.YRnSaPumXgq0UVEf8q2bkjTPOzn0bYSeHU17Up1iyCP0kEIz8l8cAOjQ-yGNNM-FF4rjWo3f8gseAkqbW746NQ';

// ── Helpers ─────────────────────────────────────────────────────────────────

let savedEnv;

before(() => {
  savedEnv = process.env.NSAUDITOR_LICENSE_KEY;
});

afterEach(() => {
  if (savedEnv !== undefined) process.env.NSAUDITOR_LICENSE_KEY = savedEnv;
  else delete process.env.NSAUDITOR_LICENSE_KEY;
  _resetCache();
});

// ── getTierFromEnv (CE default until loadLicense verifies) ──────────────────

describe('getTierFromEnv', () => {
  it('returns ce when no key set', () => {
    _resetCache();
    delete process.env.NSAUDITOR_LICENSE_KEY;
    assert.equal(getTierFromEnv(), 'ce');
  });

  it('returns ce before loadLicense even with pro key set (safe default)', () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = 'pro_test123';
    // CE is the safe default — no prefix-based tier escalation
    assert.equal(getTierFromEnv(), 'ce');
  });

  it('returns ce before loadLicense even with enterprise key set', () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = 'enterprise_test123';
    assert.equal(getTierFromEnv(), 'ce');
  });

  it('returns verified tier after loadLicense succeeds', async () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = VALID_PRO_KEY;
    await loadLicense();
    assert.equal(getTierFromEnv(), 'pro');
  });

  it('returns verified enterprise tier after loadLicense succeeds', async () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = VALID_ENTERPRISE_KEY;
    await loadLicense();
    assert.equal(getTierFromEnv(), 'enterprise');
  });

  it('returns CE after loadLicense fails (active downgrade)', async () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = EXPIRED_PRO_KEY;
    // Before loadLicense — CE default
    assert.equal(getTierFromEnv(), 'ce');
    // After loadLicense — still CE (expired key)
    await loadLicense();
    assert.equal(getTierFromEnv(), 'ce');
  });
});

// ── loadLicense ─────────────────────────────────────────────────────────────

describe('loadLicense', () => {
  it('returns CE tier when no key', async () => {
    const result = await loadLicense(undefined);
    assert.equal(result.tier, 'ce');
    assert.equal(result.valid, false);
    assert.equal(result.reason, 'no key provided');
  });

  it('validates a Pro JWT and returns correct fields', async () => {
    const result = await loadLicense(VALID_PRO_KEY);
    assert.equal(result.valid, true);
    assert.equal(result.tier, 'pro');
    assert.equal(result.org, 'test-pro@fixture.com');
    assert.equal(result.seats, 1);
    assert.ok(result.licenseId.startsWith('lic_'));
    assert.ok(Array.isArray(result.capabilities));
    assert.ok(result.capabilities.includes('intelligenceEngine'));
    assert.ok(result.capabilities.includes('brandedReports'));
    assert.ok(result.expiresAt);
  });

  it('validates an Enterprise JWT and returns correct fields', async () => {
    const result = await loadLicense(VALID_ENTERPRISE_KEY);
    assert.equal(result.valid, true);
    assert.equal(result.tier, 'enterprise');
    assert.equal(result.org, 'Test Enterprise Corp');
    assert.equal(result.seats, 25);
    assert.ok(result.capabilities.includes('cloudScanners'));
    assert.ok(result.capabilities.includes('dockerIsolation'));
    assert.ok(result.capabilities.includes('intelligenceEngine')); // includes pro caps
  });

  it('rejects expired JWT and falls back to CE', async () => {
    const result = await loadLicense(EXPIRED_PRO_KEY);
    assert.equal(result.valid, false);
    assert.equal(result.tier, 'ce');
    assert.equal(result.reason, 'invalid license key');
  });

  it('rejects tampered JWT', async () => {
    const tampered = VALID_PRO_KEY.slice(0, -2) + 'XX';
    const result = await loadLicense(tampered);
    assert.equal(result.valid, false);
    assert.equal(result.tier, 'ce');
    assert.equal(result.reason, 'invalid license key');
  });

  it('returns CE for unknown key format (no tier prefix)', async () => {
    const result = await loadLicense('garbage_key_data');
    assert.equal(result.valid, false);
    assert.equal(result.tier, 'ce');
    assert.equal(result.reason, 'unknown key format');
  });

  it('rejects prefix/tier mismatch (enterprise prefix with pro JWT)', async () => {
    const proRawJwt = VALID_PRO_KEY.slice('pro_'.length);
    const mismatchKey = 'enterprise_' + proRawJwt;
    const result = await loadLicense(mismatchKey);
    assert.equal(result.valid, false);
    assert.equal(result.tier, 'ce');
    assert.equal(result.reason, 'tier mismatch');
  });
});

// ── _resetCache ─────────────────────────────────────────────────────────────

describe('_resetCache', () => {
  it('clears verified tier so getTierFromEnv returns CE default', async () => {
    _resetCache();
    process.env.NSAUDITOR_LICENSE_KEY = VALID_PRO_KEY;
    await loadLicense();
    assert.equal(getTierFromEnv(), 'pro');

    _resetCache();
    // After reset, returns CE default (not prefix-based)
    assert.equal(getTierFromEnv(), 'ce');
  });
});

// ── Expiry warnings (subscription renewal awareness) ────────────────────────

describe('loadLicense expiry warnings', () => {
  // Dynamically generate short-lived JWTs using the license-manager keygen.
  // This avoids hardcoding fixture JWTs that drift over time.
  let generateLicenseKey, loadPrivateKey;

  before(async () => {
    const keygen = await import(join(LICENSE_MANAGER, 'lib', 'keygen.mjs'));
    const jwt = await import(join(LICENSE_MANAGER, 'lib', 'jwt.mjs'));
    generateLicenseKey = keygen.generateLicenseKey;
    loadPrivateKey = jwt.loadPrivateKey;
  });

  async function makeKey(expiresIn) {
    const privateKey = await loadPrivateKey(join(LICENSE_MANAGER, 'private', 'ec_private.pem'));
    const { key } = await generateLicenseKey('pro', {
      org: 'expiry-test@fixture.com',
      privateKey,
      expiresIn,
    });
    return key;
  }

  it('returns daysUntilExpiry and no warning for far-future keys', async () => {
    const key = await makeKey('365d');
    const result = await loadLicense(key);
    assert.equal(result.valid, true);
    assert.ok(result.daysUntilExpiry > 7);
    assert.equal(result.expiryWarning, null);
  });

  it('returns warning when key expires in ≤7 days', async () => {
    const key = await makeKey('5d');
    const result = await loadLicense(key);
    assert.equal(result.valid, true);
    assert.ok(result.daysUntilExpiry <= 7);
    assert.ok(result.expiryWarning.includes('expires in'));
    assert.ok(result.expiryWarning.includes('days'));
  });

  it('returns urgent warning when key expires in ≤1 day', async () => {
    const key = await makeKey('12h');
    const result = await loadLicense(key);
    assert.equal(result.valid, true);
    assert.equal(result.daysUntilExpiry, 0);
    assert.ok(result.expiryWarning.includes('tomorrow'));
  });

  it('returns daysUntilExpiry for valid long-lived keys', async () => {
    const result = await loadLicense(VALID_PRO_KEY);
    assert.equal(result.valid, true);
    assert.equal(typeof result.daysUntilExpiry, 'number');
    assert.ok(result.daysUntilExpiry > 300); // expires ~2036
    assert.equal(result.expiryWarning, null);
  });
});
